theme: jekyll-theme-architect
lang: "fa-IR"
dir: rtl
show_downloads : false
title: "دایرة المعارف محاوره ای کرونا"
description: "پیوندهایی که دارای اطلاعات و دستور العمل های مفید در رابطه با کویید-۱۹ است"